import base64
import hashlib
import hmac
import json
import time
from typing import Any

from pydantic import BaseModel, Field


class CallerIdentity(BaseModel):
    """Trusted caller identity claims propagated by the Gateway interceptor."""

    claims: dict[str, str] = Field(default_factory=dict)

    @property
    def subject(self) -> str | None:
        return self.claims.get("sub") or self.claims.get("oid")

    @property
    def display_name(self) -> str | None:
        return self.claims.get("preferred_username") or self.claims.get("upn")

    def audit_fields(self) -> dict[str, str]:
        fields: dict[str, str] = {}
        if self.subject:
            fields["caller_subject"] = self.subject
        if self.display_name:
            fields["caller_display_name"] = self.display_name
        for key in ("appid", "azp", "client_id", "tid"):
            if key in self.claims:
                fields[f"caller_{key}"] = self.claims[key]
        return fields


def claim_values(raw: Any) -> list[str]:
    """Normalize JWT claim values used by common OIDC providers."""

    if raw is None:
        return []
    if isinstance(raw, str):
        return raw.split()
    return [str(item) for item in raw]


def grants_from_claims(claims: dict[str, Any], accepted_claims: list[str]) -> set[str]:
    """Extract delegated scopes and app roles from configured JWT claim names."""

    grants: set[str] = set()
    for claim in accepted_claims:
        grants.update(claim_values(claims.get(claim)))
    return grants


def identity_from_claims(
    claims: dict[str, Any], identity_claims: list[str]
) -> CallerIdentity:
    """Extract the small caller identity subset allowed for Runtime propagation."""

    selected: dict[str, str] = {}
    for claim in identity_claims:
        value = claims.get(claim)
        if isinstance(value, str) and value:
            selected[claim] = value
    return CallerIdentity(claims=selected)


def encode_identity(identity: CallerIdentity) -> str:
    """Encode identity claims for a request header without introducing separators."""

    payload = json.dumps(identity.claims, separators=(",", ":"), sort_keys=True).encode()
    return base64.urlsafe_b64encode(payload).decode().rstrip("=")


def identity_from_header(raw: str | None) -> CallerIdentity:
    """Decode a trusted identity header generated by the Gateway interceptor."""

    if not raw:
        return CallerIdentity()
    try:
        padded = raw + "=" * (-len(raw) % 4)
        claims = json.loads(base64.urlsafe_b64decode(padded))
    except Exception:
        return CallerIdentity()
    if not isinstance(claims, dict):
        return CallerIdentity()
    return CallerIdentity(
        claims={str(key): str(value) for key, value in claims.items() if value is not None}
    )


def gateway_header_signature(
    secret: str, grants: str, identity: str, issued_at: str
) -> str:
    """Sign the trusted Gateway headers propagated to the Runtime."""

    payload = "\n".join([grants, identity, issued_at]).encode()
    digest = hmac.new(secret.encode(), payload, hashlib.sha256).digest()
    return base64.urlsafe_b64encode(digest).decode().rstrip("=")


def verify_gateway_header_signature(
    secret: str,
    grants: str,
    identity: str,
    issued_at: str,
    signature: str,
    *,
    ttl_seconds: int,
    now: float | None = None,
) -> bool:
    """Verify trusted Gateway headers before using them for authorization."""

    if not all([secret, issued_at, signature]):
        return False
    try:
        issued_at_seconds = int(issued_at)
    except ValueError:
        return False
    current = int(now if now is not None else time.time())
    if issued_at_seconds > current + 30:
        return False
    if current - issued_at_seconds > ttl_seconds:
        return False
    expected = gateway_header_signature(secret, grants, identity, issued_at)
    return hmac.compare_digest(expected, signature)
